apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback
spec:
  selector:
    matchLabels:
      app: rollback
  replicas: 1
  minReadySeconds: 2
  template:
    metadata:
      labels:
        app: rollback
        # agent.registration.name in the agents config -> infra-integration/charts/rollback/templates/bragent-cm.yaml
        adpbrlabelkey: eric-enm-mdt-bro-agent
      annotations:
        backupType: "ROLLBACK"
    spec:
      volumes:
        - name: state-volume
          emptyDir: { }
        - name: bragent-config
          configMap:
            name: {{ .Values.brAgent.config }}
      containers:
        - name: bragent
          image: {{ .Values.global.registry.url }}/{{ .Values.imageCredentials.repoPath }}/{{ .Values.images.bragent.name }}:{{ .Values.images.bragent.tag }}
          imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
          command: [ "/bin/sh", "-c", "/opt/ericsson/backup-restore-agent/bragent" ]
          volumeMounts:
            - mountPath: /etc/bragent/agent
              name: bragent-config
              readOnly: true
            - mountPath: /var/bragent
              name: state-volume
        - name: rollback
          image: {{ .Values.global.registry.url }}/{{ .Values.imageCredentials.repoPath }}/{{ .Values.images.eric_enm_sles.name }}:{{ .Values.images.eric_enm_sles.tag }}
          imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
          command: [ "/bin/sh", "-c", "while true; do sleep 1; done" ]
          env:
          - name: BRO_HOST
            value: {{ .Values.brAgent.broServiceName }}
          - name: BRO_PORT
            value: {{ .Values.brAgent.broServicePort | quote }}
