eric-ctrl-bro:
  persistence:
    persistentVolumeClaim:
      size: "1Gi"
  resources:
    backupAndRestore:
      limits:
        cpu: "1"
        memory: "1Gi"
        ephemeral-storage: "1Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
        ephemeral-storage: "500Mi"
