name: infra-integration
description: A Helm chart to test post-install hooks.
type: application
apiVersion: v2
appVersion: "1.0"
version: 0.1.0
dependencies:
  - name: restore
    version: 0.1.0
  - name: rollback
    version: 0.1.0
