apiVersion: v1
kind: Pod
metadata:
  name: brocli
  labels:
    app: brocli
spec:
  serviceAccountName: "eric-enm-bro-integration"
  containers:
    - name: hookdev
      image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/backup-restore-cli:latest
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done" ]
      env:
        - name: BRO_HOST
          value: {{ .Values.brAgent.broServiceName }}
        - name: BRO_PORT
          value: {{ .Values.brAgent.broServicePort | quote }}