# Chart hooks are not managed by tiller, so we've to delete them ourselves.
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-uninstall-cleanup-hook"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    chart: {{ template "infra-integration.chart" . }}
    app.kubernetes.io/name: {{ template "infra-integration.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}-uninstall-cleanup-hook"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ template "infra-integration.chart" . }}
        helm.sh/chart: {{ template "infra-integration.chart" . }}
    spec:
      restartPolicy: Never
      serviceAccountName: "{{ .Values.global.restore.serviceaccount -}}"
      containers:
        - name: executor
          image: {{ .Values.global.registry.url }}/{{ .Values.imageCredentials.repoPath }}/{{ index .Values "images" "eric-enm-chart-hooks" "name" }}:{{ index .Values "images" "eric-enm-chart-hooks" "tag" }}
          imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - exec_hook delete_hook_jobs.py -j {{ template "infra-integration.broRestoreTriggerJobName" . }} -j {{ template "infra-integration.broRestoreExecutorJobName" . }} -j {{ template "infra-integration.broRestoreReportJobName" . }}
